#!/usr/bin/env bash

echo "Type in the public SSH key to be added:"
read -r key

keyfile=$(mktemp) && echo "$key" > "$keyfile"
fingerprint=$(ssh-keygen -lf "$keyfile")

if [ "$(echo "$fingerprint" | grep -cE '(R|D)SA')" -eq 0 ]
then
  echo "Error: $fingerprint"
  rm "$keyfile"
  exit 1
fi

echo -n "no-agent-forwarding,no-port-forwarding,no-X11-forwarding " >> .ssh/authorized_keys && \
cat "$keyfile" >> .ssh/authorized_keys
rm "$keyfile"

echo "Success: added a key $fingerprint"
