#!/usr/bin/env bash

dir="$(pwd)/$(dirname "${BASH_SOURCE[0]}")"

if [ $# -eq 0 ]
then
  echo "Usage: $0 <project.git>"
  exit 1
fi

project="$(basename "$1" ".git").git"
target="${GIT_BASE_DIR}/${project}"

echo "Type in a description for the project:"
read -r description

git init --bare --template="${dir}/template" "${target}"

echo "${target}/${description}" > description

echo "Success: added a new project $project"
