#!/usr/bin/env bash

date '+[%Y-%m-%d %H:%M:%S]'
refname=$1

if [[ $refname == "refs/tags/deploy" ]]
then
  if [[ -f $refname ]]
  then
    echo "[DEPLOY] $rev"
    rev=$(cat $refname)
    rm -rf releases/$rev
    mkdir -p releases/$rev
    git archive $rev | tar -xf - -C releases/$rev
    [ -d shared ] && cp -R shared/. releases/$rev
    pushd releases/$rev
    docker-compose --file local.ci.yml up --detach && push "[DEPLOY] $(pwd)"
    popd
    rm -rf current
    ln -s releases/$rev current
  else
    echo "[ HALT ] $(readlink current | cut -d'/' -f2)"
    pushd current
    docker-compose --file local.ci.yml stop
    popd
    mv current old
  fi
fi

exit 0

