#!/usr/bin/env bash

if [ $# -eq 0 ]
then
  echo "Usage: $0 <project.git>"
  exit 1
fi

read -rp "Continue [y/N]? " choice
case "$choice" in
  y|Y ) ;;
  * ) exit 0;;
esac

project="$(basename "$1" ".git").git"
target="${GIT_BASE_DIR}/${project}"

rm -rf "$target"

echo "Success: removed a project $project"
