#!/usr/bin/env bash

if [ $# -lt 3 ]
then
  echo "Usage: $0 <project.git> <service> <command>"
  exit 1
fi

project=$(echo "$1" | sed 's/\.git$\|$/.git/i')
service=$2
shift 2
cmd=$*

if [[ ! -d "$GIT_DIR_BASE/$project" ]]
then
  echo "Error: cannot find project $project"
  exit 1
fi

target="$GIT_DIR_BASE/$project/current"

if [[ ! -d "$target" ]]
then
  echo "Error: project $project is not deployed"
  exit 1
fi

pushd $target
docker-compose --file local.ci.yml ps -q $service
docker-compose --file local.ci.yml run $service $cmd
popd
